# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1138, 604)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 451, 341))
        self.groupBox.setObjectName("groupBox")
        self.cameraPreview = QtWidgets.QWidget(self.groupBox)
        self.cameraPreview.setGeometry(QtCore.QRect(0, 20, 451, 301))
        self.cameraPreview.setObjectName("cameraPreview")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(10, 320, 431, 16))
        self.label_8.setObjectName("label_8")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 360, 451, 181))
        self.groupBox_2.setObjectName("groupBox_2")
        self.connectButton = QtWidgets.QPushButton(self.groupBox_2)
        self.connectButton.setGeometry(QtCore.QRect(160, 20, 121, 32))
        self.connectButton.setObjectName("connectButton")
        self.connectionStatusLabel = QtWidgets.QLabel(self.groupBox_2)
        self.connectionStatusLabel.setGeometry(QtCore.QRect(10, 20, 141, 28))
        self.connectionStatusLabel.setObjectName("connectionStatusLabel")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(10, 50, 141, 28))
        self.label_5.setObjectName("label_5")
        self.contShootButton = QtWidgets.QPushButton(self.groupBox_2)
        self.contShootButton.setGeometry(QtCore.QRect(160, 50, 121, 32))
        self.contShootButton.setObjectName("contShootButton")
        self.shutterSpeedCombo = QtWidgets.QComboBox(self.groupBox_2)
        self.shutterSpeedCombo.setGeometry(QtCore.QRect(164, 90, 114, 26))
        self.shutterSpeedCombo.setObjectName("shutterSpeedCombo")
        self.ISOCombo = QtWidgets.QComboBox(self.groupBox_2)
        self.ISOCombo.setGeometry(QtCore.QRect(164, 120, 114, 26))
        self.ISOCombo.setObjectName("ISOCombo")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(10, 90, 141, 24))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(10, 120, 141, 24))
        self.label_7.setObjectName("label_7")
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_5.setGeometry(QtCore.QRect(290, 20, 151, 131))
        self.groupBox_5.setObjectName("groupBox_5")
        self.cpBlue = QtWidgets.QRadioButton(self.groupBox_5)
        self.cpBlue.setGeometry(QtCore.QRect(10, 100, 100, 20))
        self.cpBlue.setObjectName("cpBlue")
        self.colorProcessingGroup = QtWidgets.QButtonGroup(MainWindow)
        self.colorProcessingGroup.setObjectName("colorProcessingGroup")
        self.colorProcessingGroup.addButton(self.cpBlue)
        self.cpMonochrome = QtWidgets.QRadioButton(self.groupBox_5)
        self.cpMonochrome.setGeometry(QtCore.QRect(10, 40, 100, 20))
        self.cpMonochrome.setObjectName("cpMonochrome")
        self.colorProcessingGroup.addButton(self.cpMonochrome)
        self.cpRed = QtWidgets.QRadioButton(self.groupBox_5)
        self.cpRed.setGeometry(QtCore.QRect(10, 60, 100, 20))
        self.cpRed.setObjectName("cpRed")
        self.colorProcessingGroup.addButton(self.cpRed)
        self.cpGreen = QtWidgets.QRadioButton(self.groupBox_5)
        self.cpGreen.setGeometry(QtCore.QRect(10, 80, 100, 20))
        self.cpGreen.setObjectName("cpGreen")
        self.colorProcessingGroup.addButton(self.cpGreen)
        self.cpColor = QtWidgets.QRadioButton(self.groupBox_5)
        self.cpColor.setGeometry(QtCore.QRect(10, 20, 100, 20))
        self.cpColor.setChecked(True)
        self.cpColor.setObjectName("cpColor")
        self.colorProcessingGroup.addButton(self.cpColor)
        self.saveImgButton = QtWidgets.QPushButton(self.groupBox_2)
        self.saveImgButton.setGeometry(QtCore.QRect(310, 150, 113, 32))
        self.saveImgButton.setObjectName("saveImgButton")
        self.fittingCombo = QtWidgets.QComboBox(self.groupBox_2)
        self.fittingCombo.setGeometry(QtCore.QRect(164, 150, 114, 26))
        self.fittingCombo.setObjectName("fittingCombo")
        self.label_12 = QtWidgets.QLabel(self.groupBox_2)
        self.label_12.setGeometry(QtCore.QRect(10, 150, 141, 24))
        self.label_12.setObjectName("label_12")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(480, 10, 281, 171))
        self.groupBox_3.setObjectName("groupBox_3")
        self.spotAPreview = QtWidgets.QWidget(self.groupBox_3)
        self.spotAPreview.setGeometry(QtCore.QRect(0, 20, 151, 151))
        self.spotAPreview.setObjectName("spotAPreview")
        self.spotAZoomSlider = QtWidgets.QSlider(self.groupBox_3)
        self.spotAZoomSlider.setGeometry(QtCore.QRect(160, 40, 111, 22))
        self.spotAZoomSlider.setMaximum(6)
        self.spotAZoomSlider.setPageStep(2)
        self.spotAZoomSlider.setOrientation(QtCore.Qt.Horizontal)
        self.spotAZoomSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.spotAZoomSlider.setTickInterval(2)
        self.spotAZoomSlider.setObjectName("spotAZoomSlider")
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setGeometry(QtCore.QRect(160, 20, 81, 16))
        self.label.setObjectName("label")
        self.spotAZoomLabel = QtWidgets.QLabel(self.groupBox_3)
        self.spotAZoomLabel.setGeometry(QtCore.QRect(230, 20, 41, 16))
        self.spotAZoomLabel.setObjectName("spotAZoomLabel")
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setGeometry(QtCore.QRect(160, 70, 111, 16))
        self.label_3.setObjectName("label_3")
        self.spotAFitTable = QtWidgets.QTableWidget(self.groupBox_3)
        self.spotAFitTable.setGeometry(QtCore.QRect(150, 90, 131, 81))
        self.spotAFitTable.setObjectName("spotAFitTable")
        self.spotAFitTable.setColumnCount(0)
        self.spotAFitTable.setRowCount(0)
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(480, 180, 281, 171))
        self.groupBox_4.setObjectName("groupBox_4")
        self.spotBPreview = QtWidgets.QWidget(self.groupBox_4)
        self.spotBPreview.setGeometry(QtCore.QRect(0, 20, 151, 151))
        self.spotBPreview.setObjectName("spotBPreview")
        self.spotBZoomSlider = QtWidgets.QSlider(self.groupBox_4)
        self.spotBZoomSlider.setGeometry(QtCore.QRect(160, 40, 111, 22))
        self.spotBZoomSlider.setMaximum(6)
        self.spotBZoomSlider.setPageStep(2)
        self.spotBZoomSlider.setOrientation(QtCore.Qt.Horizontal)
        self.spotBZoomSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.spotBZoomSlider.setTickInterval(2)
        self.spotBZoomSlider.setObjectName("spotBZoomSlider")
        self.label_2 = QtWidgets.QLabel(self.groupBox_4)
        self.label_2.setGeometry(QtCore.QRect(160, 20, 81, 16))
        self.label_2.setObjectName("label_2")
        self.spotBZoomLabel = QtWidgets.QLabel(self.groupBox_4)
        self.spotBZoomLabel.setGeometry(QtCore.QRect(230, 20, 41, 16))
        self.spotBZoomLabel.setObjectName("spotBZoomLabel")
        self.label_4 = QtWidgets.QLabel(self.groupBox_4)
        self.label_4.setGeometry(QtCore.QRect(160, 70, 111, 16))
        self.label_4.setObjectName("label_4")
        self.spotBFitTable = QtWidgets.QTableWidget(self.groupBox_4)
        self.spotBFitTable.setGeometry(QtCore.QRect(150, 90, 131, 81))
        self.spotBFitTable.setObjectName("spotBFitTable")
        self.spotBFitTable.setColumnCount(0)
        self.spotBFitTable.setRowCount(0)
        self.groupBox_6 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_6.setGeometry(QtCore.QRect(480, 360, 281, 181))
        self.groupBox_6.setObjectName("groupBox_6")
        self.burstnumberInput = QtWidgets.QSpinBox(self.groupBox_6)
        self.burstnumberInput.setGeometry(QtCore.QRect(110, 22, 48, 24))
        self.burstnumberInput.setMinimum(1)
        self.burstnumberInput.setMaximum(100)
        self.burstnumberInput.setObjectName("burstnumberInput")
        self.label_9 = QtWidgets.QLabel(self.groupBox_6)
        self.label_9.setGeometry(QtCore.QRect(10, 22, 81, 24))
        self.label_9.setObjectName("label_9")
        self.saveResultsCB = QtWidgets.QCheckBox(self.groupBox_6)
        self.saveResultsCB.setGeometry(QtCore.QRect(10, 50, 101, 20))
        self.saveResultsCB.setChecked(True)
        self.saveResultsCB.setObjectName("saveResultsCB")
        self.startBurstButton = QtWidgets.QPushButton(self.groupBox_6)
        self.startBurstButton.setGeometry(QtCore.QRect(170, 20, 101, 32))
        self.startBurstButton.setObjectName("startBurstButton")
        self.outputDirDisplay = QtWidgets.QLineEdit(self.groupBox_6)
        self.outputDirDisplay.setGeometry(QtCore.QRect(10, 120, 257, 21))
        self.outputDirDisplay.setReadOnly(True)
        self.outputDirDisplay.setObjectName("outputDirDisplay")
        self.browseOutputDirButton = QtWidgets.QPushButton(self.groupBox_6)
        self.browseOutputDirButton.setGeometry(QtCore.QRect(172, 90, 101, 32))
        self.browseOutputDirButton.setObjectName("browseOutputDirButton")
        self.label_10 = QtWidgets.QLabel(self.groupBox_6)
        self.label_10.setGeometry(QtCore.QRect(10, 90, 151, 30))
        self.label_10.setObjectName("label_10")
        self.outputPrefixInput = QtWidgets.QLineEdit(self.groupBox_6)
        self.outputPrefixInput.setGeometry(QtCore.QRect(150, 150, 117, 21))
        self.outputPrefixInput.setObjectName("outputPrefixInput")
        self.label_11 = QtWidgets.QLabel(self.groupBox_6)
        self.label_11.setGeometry(QtCore.QRect(10, 150, 121, 21))
        self.label_11.setObjectName("label_11")
        self.saveCropsOnlyCB = QtWidgets.QCheckBox(self.groupBox_6)
        self.saveCropsOnlyCB.setGeometry(QtCore.QRect(10, 70, 191, 20))
        self.saveCropsOnlyCB.setChecked(True)
        self.saveCropsOnlyCB.setObjectName("saveCropsOnlyCB")
        self.spotAIntensityBox = QtWidgets.QGroupBox(self.centralwidget)
        self.spotAIntensityBox.setGeometry(QtCore.QRect(780, 10, 341, 261))
        self.spotAIntensityBox.setObjectName("spotAIntensityBox")
        self.spotAIntensity = QtWidgets.QWidget(self.spotAIntensityBox)
        self.spotAIntensity.setGeometry(QtCore.QRect(0, 20, 341, 241))
        self.spotAIntensity.setObjectName("spotAIntensity")
        self.spotBIntensityBox = QtWidgets.QGroupBox(self.centralwidget)
        self.spotBIntensityBox.setGeometry(QtCore.QRect(780, 280, 341, 261))
        self.spotBIntensityBox.setObjectName("spotBIntensityBox")
        self.spotBIntensity = QtWidgets.QWidget(self.spotBIntensityBox)
        self.spotBIntensity.setGeometry(QtCore.QRect(0, 20, 341, 241))
        self.spotBIntensity.setObjectName("spotBIntensity")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1138, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuDIMM_Control = QtWidgets.QMenu(self.menuBar)
        self.menuDIMM_Control.setObjectName("menuDIMM_Control")
        MainWindow.setMenuBar(self.menuBar)
        self.actionVersion_0_0_1 = QtWidgets.QAction(MainWindow)
        self.actionVersion_0_0_1.setEnabled(False)
        self.actionVersion_0_0_1.setObjectName("actionVersion_0_0_1")
        self.actionLoadImage = QtWidgets.QAction(MainWindow)
        self.actionLoadImage.setObjectName("actionLoadImage")
        self.menuDIMM_Control.addAction(self.actionLoadImage)
        self.menuDIMM_Control.addSeparator()
        self.menuDIMM_Control.addAction(self.actionVersion_0_0_1)
        self.menuBar.addAction(self.menuDIMM_Control.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "DIMM Control"))
        self.groupBox.setTitle(_translate("MainWindow", "Camera image"))
        self.label_8.setText(_translate("MainWindow", "Left-click to select spot A position; right-click for spot B"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Imaging settings"))
        self.connectButton.setText(_translate("MainWindow", "Connect"))
        self.connectionStatusLabel.setText(_translate("MainWindow", "Not connected"))
        self.label_5.setText(_translate("MainWindow", "Cont. single shooting"))
        self.contShootButton.setText(_translate("MainWindow", "Start"))
        self.label_6.setText(_translate("MainWindow", "Shutter speed"))
        self.label_7.setText(_translate("MainWindow", "ISO exposure"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Color processing"))
        self.cpBlue.setText(_translate("MainWindow", "Blue layer"))
        self.cpMonochrome.setText(_translate("MainWindow", "Monochrome"))
        self.cpRed.setText(_translate("MainWindow", "Red layer"))
        self.cpGreen.setText(_translate("MainWindow", "Green layer"))
        self.cpColor.setText(_translate("MainWindow", "Color"))
        self.saveImgButton.setText(_translate("MainWindow", "Save image"))
        self.label_12.setText(_translate("MainWindow", "Fitting method"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Spot A"))
        self.label.setText(_translate("MainWindow", "Zoom level"))
        self.spotAZoomLabel.setText(_translate("MainWindow", "1x"))
        self.label_3.setText(_translate("MainWindow", "Fit parameters"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Spot B"))
        self.label_2.setText(_translate("MainWindow", "Zoom level"))
        self.spotBZoomLabel.setText(_translate("MainWindow", "1x"))
        self.label_4.setText(_translate("MainWindow", "Fit parameters"))
        self.groupBox_6.setTitle(_translate("MainWindow", "DIMM measurement settings"))
        self.label_9.setText(_translate("MainWindow", "Burst length"))
        self.saveResultsCB.setText(_translate("MainWindow", "Save results"))
        self.startBurstButton.setText(_translate("MainWindow", "Start"))
        self.browseOutputDirButton.setText(_translate("MainWindow", "Browse"))
        self.label_10.setText(_translate("MainWindow", "Output directory"))
        self.label_11.setText(_translate("MainWindow", "Output files prefix"))
        self.saveCropsOnlyCB.setText(_translate("MainWindow", "Save cropped images only"))
        self.spotAIntensityBox.setTitle(_translate("MainWindow", "Spot A intensity profile"))
        self.spotBIntensityBox.setTitle(_translate("MainWindow", "Spot B intensity profile"))
        self.menuDIMM_Control.setTitle(_translate("MainWindow", "DIMM Control"))
        self.actionVersion_0_0_1.setText(_translate("MainWindow", "version 0.0.1"))
        self.actionLoadImage.setText(_translate("MainWindow", "Load image..."))

